import Image from "next/image";
import { Eye, Handshake, Heart, Leaf, ShieldCheck, Target, Users } from "lucide-react";
import { PageHero } from "@/components/page-hero";
import { createPageMetadata } from "@/lib/seo";

export const metadata = createPageMetadata({
  title: "Empresa",
  description:
    "Conheça a história da Orgus Indústria, fabricante brasileira de faróis automotivos desde 1981, sua missão, visão, valores e política da qualidade.",
  path: "/empresa",
});

const values = [
  { icon: Eye, title: "Transparência organizacional", text: "Somos éticos e transparentes em nossas relações." },
  { icon: Handshake, title: "Comprometimento", text: "Damos o nosso melhor para superar expectativas, investindo nas pessoas e na qualidade do que entregamos." },
  { icon: Heart, title: "Respeito", text: "Valorizamos cada pessoa, celebramos as diferenças e tratamos todos com igualdade e dignidade." },
  { icon: ShieldCheck, title: "Segurança e responsabilidade", text: "Mantemos um ambiente de trabalho seguro e agimos com total respeito ao meio ambiente." },
];

export default function CompanyPage() {
  return <main>
    <PageHero eyebrow="A Orgus" title="Uma indústria movida por qualidade." text="Desde 1981, unimos conhecimento, tecnologia e pessoas para desenvolver soluções de iluminação automotiva." image="/images/empresa-producao.jpg"/>
    <section className="py-20 lg:py-28"><div className="site-container grid gap-14 lg:grid-cols-[1fr_.92fr] lg:items-center"><div><span className="eyebrow">Nossa trajetória</span><h2 className="section-title">Mais de quatro décadas iluminando caminhos.</h2><div className="mt-7 space-y-5 text-lg leading-8 text-slate-600"><p>Fundada em 1981, a Orgus sempre esteve voltada à fabricação de faróis automotivos. Ao longo dessa trajetória, investimentos constantes em pesquisa tecnológica, equipamentos, mão de obra especializada e instalações modernas mantiveram a empresa conectada às exigências do setor.</p><p>Essa evolução permite oferecer produtos eficientes e um atendimento próximo, ao mesmo tempo em que promove o desenvolvimento dos colaboradores e um crescimento responsável e sustentável.</p><p>Nosso compromisso é fabricar e comercializar produtos e serviços com excelência, qualidade e respeito em todas as relações.</p></div></div><div className="grid gap-4 sm:grid-cols-2"><div className="relative min-h-80 overflow-hidden rounded-2xl sm:translate-y-7"><Image src="/images/empresa-fachada.jpg" alt="Fachada da Orgus Indústria" fill sizes="(max-width: 640px) 100vw, 25vw" className="object-cover"/></div><div className="relative min-h-80 overflow-hidden rounded-2xl"><Image src="/images/empresa-frota.jpg" alt="Frota em frente à unidade industrial" fill sizes="(max-width: 640px) 100vw, 25vw" className="object-cover"/></div></div></div></section>
    <section className="bg-[#f2f6fc] py-20 lg:py-28"><div className="site-container grid gap-6 lg:grid-cols-2"><article className="rounded-2xl bg-[#173e90] p-8 text-white sm:p-11"><Target size={35} className="text-blue-200"/><p className="mt-8 text-sm font-extrabold uppercase tracking-[.18em] text-blue-200">Missão</p><h2 className="mt-3 text-2xl font-black leading-tight sm:text-3xl">Ser referência no fornecimento de autopeças de qualidade.</h2><p className="mt-4 leading-7 text-white/70">Atender com excelência às necessidades e expectativas dos nossos clientes.</p></article><article className="rounded-2xl bg-[#0a1d43] p-8 text-white sm:p-11"><Eye size={35} className="text-blue-200"/><p className="mt-8 text-sm font-extrabold uppercase tracking-[.18em] text-blue-200">Visão</p><h2 className="mt-3 text-2xl font-black leading-tight sm:text-3xl">Ser reconhecida no Brasil e no mundo.</h2><p className="mt-4 leading-7 text-white/70">Consolidar nossa referência na fabricação de faróis e peças plásticas técnicas automotivas nos mercados nacional e internacional.</p></article></div></section>
    <section className="py-20 lg:py-28"><div className="site-container"><span className="eyebrow">Nossos valores</span><h2 className="section-title">Princípios presentes em tudo o que fazemos.</h2><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{values.map(({icon: Icon,title,text})=><article key={title} className="industrial-card rounded-2xl p-7"><Icon className="text-[#3274db]" size={30}/><h3 className="mt-6 text-lg font-extrabold">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{text}</p></article>)}</div><p className="mx-auto mt-12 max-w-3xl text-center text-lg leading-8 text-slate-600">Nosso comprometimento é disseminar essa visão, realizar nossa missão e viver esses valores junto a colaboradores, clientes e fornecedores.</p></div></section>
    <section className="bg-[#081a3c] py-20 text-white"><div className="site-container grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><span className="text-sm font-extrabold uppercase tracking-[.18em] text-blue-300">Política da qualidade</span><h2 className="mt-4 text-4xl font-black tracking-tight">Excelência sustentada por quatro pilares.</h2></div><div className="grid gap-6 sm:grid-cols-2">{[{icon: Users,title:"Clientes",text:"Entendemos suas expectativas e nos dedicamos a atendê-las, da produção ao pós-venda."},{icon: Target,title:"Melhoria contínua",text:"Revisamos e aperfeiçoamos constantemente processos, produtos e serviços."},{icon: Users,title:"Pessoas",text:"Desenvolvemos colaboradores por meio de treinamentos e capacitações periódicas."},{icon: Leaf,title:"Ética e transparência",text:"Agimos com responsabilidade e honestidade em todas as nossas relações."}].map(({icon:Icon,title,text})=><div key={title} className="border-l-2 border-blue-400 pl-5"><Icon className="text-blue-300" size={22}/><h3 className="mt-3 font-extrabold">{title}</h3><p className="mt-2 text-sm leading-6 text-white/60">{text}</p></div>)}</div></div></section>
  </main>;
}
